version: "3"

services:

  radius-mysql:
    image: mariadb:10.3
    container_name: radius-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=radiusrootdbpw
    volumes:
      - "$DOCKER_DIR/daloradius/mysql:/var/lib/mysql"

  radius:
    container_name: radius
    build:
      context: .
      dockerfile: Dockerfile-freeradius
    restart: unless-stopped
    depends_on: 
      - radius-mysql
    ports:
      - '1812:1812/udp'
      - '1813:1813/udp'
    environment:
      - MYSQL_HOST=radius-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      # Optional settings
      - DEFAULT_CLIENT_SECRET=testing123
    volumes:
      - $DOCKER_DIR/daloradius/freeradius:/data
    # If you want to disable debug output, remove the command parameter
    command: -X

  radius-web:
    build: .
    container_name: radius-web
    restart: unless-stopped
    depends_on:
      - radius
      - radius-mysql
    ports:
      - '81:80'
    environment:
      - MYSQL_HOST=radius-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      # Optional Settings:
      - DEFAULT_CLIENT_SECRET=testing123
      - DEFAULT_FREERADIUS_SERVER=radius
      - MAIL_SMTPADDR=127.0.0.1
      - MAIL_PORT=25
      - MAIL_FROM=root@daloradius.xdsl.by
      - MAIL_AUTH=
    volumes:
      - $DOCKER_DIR/daloradius/daloradius:/data

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PUID=1001
      - PGID=998
      - TZ=Europe/Moscow
      - PMA_ARBITRARY=0 #optional
      - PMA_HOST=radius-mysql
#      - PMA_USER=root
#      - PMA_ABSOLUTE_URI=https://phpmyadmin.example.com #optional
    volumes:
      - $DOCKER_DIR/daloradius/phpmyadmin:/config
    ports:
      - 82:80
    restart: unless-stopped
